// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkb-rJe0mNBA_hhMa3uiIBbaYEh6MY_0w',
    appId: '1:520138345207:web:06122cbc3292287ba961f2',
    messagingSenderId: '520138345207',
    projectId: 'spotify-clone-41988',
    authDomain: 'spotify-clone-41988.firebaseapp.com',
    storageBucket: 'spotify-clone-41988.firebasestorage.app',
    measurementId: 'G-R1LLCW0CF8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeB0bVAJqaJqGVEnG4iBxMXOAcXeCsGec',
    appId: '1:520138345207:android:640ab32268aadb49a961f2',
    messagingSenderId: '520138345207',
    projectId: 'spotify-clone-41988',
    storageBucket: 'spotify-clone-41988.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbIZW-WStVvlZUFOPkxf7Q4E0aKpI4YgQ',
    appId: '1:520138345207:ios:2a4865d31039ee00a961f2',
    messagingSenderId: '520138345207',
    projectId: 'spotify-clone-41988',
    storageBucket: 'spotify-clone-41988.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbIZW-WStVvlZUFOPkxf7Q4E0aKpI4YgQ',
    appId: '1:520138345207:ios:2a4865d31039ee00a961f2',
    messagingSenderId: '520138345207',
    projectId: 'spotify-clone-41988',
    storageBucket: 'spotify-clone-41988.firebasestorage.app',
    iosBundleId: 'com.example.spotify',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCkb-rJe0mNBA_hhMa3uiIBbaYEh6MY_0w',
    appId: '1:520138345207:web:ba463384036fd2dda961f2',
    messagingSenderId: '520138345207',
    projectId: 'spotify-clone-41988',
    authDomain: 'spotify-clone-41988.firebaseapp.com',
    storageBucket: 'spotify-clone-41988.firebasestorage.app',
    measurementId: 'G-G2JDBN2VLD',
  );
}
